language: bash
os:
  - linux
  - osx
addons:
  apt:
    update: true
    packages:
      - openvpn
      - jq
  homebrew:
    update: true
    packages:
      - openvpn
      - jq

before_install:
  - git submodule init
  - perl --version
script:
  - cd tests
  - ./get_my_region_test.sh
  - ./get_my_token_test.sh
  - ./get_signature_test.sh
  - ./connect_test.sh