language: bash
os:
  - linux
  - osx
addons:
  apt:
    update: true
    packages:
      - openvpn
      - jq
  homebrew:
    update: true
    packages:
      - jq

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install --build-from-source openvpn; fi
script:
  - cd tests
  - ./get_my_region_test.sh
  - ./get_my_token_test.sh
  - ./get_signature_test.sh
  - ./connect_test.sh