language: bash
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - openvpn

before_install:
  - git submodule init
script:
  - cd tests
  - ./get_my_region_test.sh
  - ./get_my_token_test.sh
  - ./get_signature_test.sh
  - ./connect_test.sh