language: bash
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - openvpn
      - jq

before_install:
  - git submodule init
  - perl --version
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install jq; fi
script:
  - cd tests
  - ./get_my_region_test.sh
  - ./get_my_token_test.sh
  - ./get_signature_test.sh
  - ./connect_test.sh